# fly.toml app configuration file generated for my-vault-model on 2025-12-06T18:56:29+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-vault-model'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'model_data'
  destination = '/models'
  initial_size = '10gb'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]   # tls first, then http

[[vm]]
  size = 'shared-cpu-4x'
  memory = '8gb'
