# fly.toml app configuration file generated for my-vault-model on 2025-12-06T07:28:09+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-vault-model'
primary_region = 'syd'

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false  # DISABLE THIS temporarily!
  auto_start_machines = true
  min_machines_running = 1    # Keep 1 running so it finishes the download

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1