# fly.toml app configuration file generated for my-vault-model on 2025-12-06T18:56:29+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-vault-model'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'model_data'
  destination = '/models'
  initial_size = '10gb'

[http_service]
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-4x'
  memory = '8gb'
